server.port: 8182
server.session.timeout: 360000 #10h

solon.app:
  group: "sponge"
  name: "spongeadmin"
  title: "SPONGE"

solon.cloud.water:
  server: "waterapi"
  config:
    load: "water_bcf::bcf.yml"
  log:
    default: "sponge_log_admin"

solon.logging.logger:
  "org.eclipse.jetty.*":
    level: INFO
  "com.zaxxer.hikari.*":
    level: INFO
  "org.apache.*":
    level: INFO

srww.weed.track.enable: false