server.port: 8171
server.session.timeout: 360000 #10h

solon.app:
  group: "sponge"
  name: "spongeadmin"
  title: "SPONGE"

solon.cloud.water:
  server: "waterapi:9371"
  config:
    load: "grit:grit.yml,grit:gritclient.yml"
  log:
    default: "sponge_log_admin"

solon.logging.logger:
  "org.eclipse.jetty.*":
    level: INFO
  "com.zaxxer.hikari.*":
    level: INFO
  "org.apache.*":
    level: INFO

srww.wood.track.enable: false