server.port: 8182
server.session.timeout: 7200

solon.app:
  group: "sponge"
  name: "spongeadmin"
  title: "SPONGE"

solon.cloud.water:
  server: "waterapi.water"
  config:
    loadGroup: "water_bcf"
    loadKey: "bcf.yml"
  log:
    default: sponge_log_admin


solon.logging.logger:
  "org.eclipse.jetty.*":
    level: INFO
  "com.zaxxer.hikari.*":
    level: INFO
  "org.apache.*":
    level: INFO

srww.weed.track.enable: false