server.port: 8182
server.session.timeout: 7200

solon.app:
  group: "sponge"
  name: "spongeadmin"
  title: "SPONGE"

solon.cloud.water:
  server: "water"
  config:
    loadGroup: "water_bcf"
    loadKey: "bcf.yml"
  log:
    default: sponge_log_admin



srww.weed.track.enable: false